### ISSUE TITLE
Relu() between MobiusLinear

### ISSUE THREAD

**Issue by ShaoTengLiu** [ferrine/hyrnn#13]
Hi, I am wondering if I can add a **relu()** between two **MobiusLinear**. Have you designed a hyperbolic relu()?

**Comment by ferrine** [comment]
Hi, you can use this method to apply a nonlinearity
https://github.com/geoopt/geoopt/blob/master/geoopt/manifolds/poincare/__init__.py#L205

But you may have a valid concern that pointwise nonlinearity is senseless.
You may want to try a radial version of nonlinearity, but it is not
implemented in the core.

**Comment by ShaoTengLiu** [comment]
Thanks a lot!
