### ISSUE TITLE
ModuleNotFoundError: No module named 'geoopt.manifolds.poincare'

### ISSUE THREAD

**Issue by SkyFishMoon** [ferrine/hyrnn#15]
Hi, I meet a problem  when I run the run.py. Does this error comes from the update of geoopt? I also find that there is a class named PoincareBall in geoopt.manifolds.stereographic, Is this and geoopt.manifolds.poincare the same?

**Comment by martinwhl** [comment]
The geoopt package has updated and replaced poincare model with k-stereographic model. Use k-stereographic model with k = -1/c, or use the older version of geoopt (0.1.2) should help.

**Comment by ferrine** [comment]
Yes, there was a huge update

**Comment by SkyFishMoon** [comment]
Got it. Thanks
