### ISSUE TITLE
Update the using of newest packedges geoopt and catalyst.

### ISSUE THREAD

**Issue by CheriseZhu** [ferrine/hyrnn#9]
The latest version of hyrnn uses: "geoopt.PoincareBall(c=c).set_default_order(order)" that encounters a problem: "AttributeError: 'PoincareBall' object has no attribute 'set_default_order'". And there are some other problems. So, the latest version of hyrnn should be updated to meet the newest packedges catalyst and geoopt.

**Comment by ferrine** [comment]
Yeah, we had a major update in geoopt, we will include the updates once we finish with geoopt refactoring

**Comment by ferrine** [comment]
Particularly we are waiting for https://github.com/geoopt/geoopt/pull/78 and a followup PR that will implement random initialization on manifolds

**Comment by CheriseZhu** [comment]
Looking forward to the updated version of geoopt!

**Comment by rrkarim** [comment]
Since https://github.com/geoopt/geoopt/pull/78 is ready. I don't think we need too many changes here. Removing `order` logic from the code (arguments and methods) does the job. Also adaptation to the pytorch api would be great.
